version: '3.8'

services:
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /home/ubuntu/grafana:/mnt/config
    command:
      - "--config.file=/mnt/config/loki-config.yaml"

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - /home/ubuntu/grafana:/mnt/config
      - /home/ubuntu/.pm2/logs:/home/ubuntu/.pm2/logs
    depends_on:
      - loki
    command:
      - "--config.file=/mnt/config/promtail-config.yaml"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yaml:/mnt/config/prometheus.yml
    command:
      - "--config.file=/mnt/config/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/grafana:/etc/grafana/provisioning
    depends_on:
      - loki
      - prometheus
